config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :shows, only: [:index]
  resources :favorites, only: [:create, :destroy]
  root 'shows#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
	has_many :shows, dependent: :destroy
	validates :name, presence: true, uniqueness: true
end

app/models/favorite_user_show.rb
class FavoriteUserShow < ApplicationRecord
	belongs_to :user
	belongs_to :show

	after_create :create_job
	before_destroy :delete_job

	def create_job
		job_id = SendEmailWorker.perform_in(30.minutes, user_id, show_id)
		self.update(reminder_job_id: job_id)
	end

	def delete_job
		require 'sidekiq/api'
		queue = Sidekiq::Queue.new('default')
		queue.find_job(reminder_job_id).delete if queue.find_job(reminder_job_id).present?
	end
end

app/models/show.rb
class Show < ApplicationRecord
	belongs_to :channel
	has_many :favorite_user_shows
	has_many :favorite_users, through: :favorite_user_shows, source: 'user'
	validates :name, :start_time, :end_time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorite_user_shows
	has_many :favorite_shows, through: :favorite_user_shows, source: :show

	def added_in_favorites(show_id)
		favorite_shows.ids.include?(show_id)
	end
end
	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :check_user

	def create
		@show = Show.find_by(id: params[:show_id])
		favorite_show = current_user.favorite_user_shows.build(show_id: @show.id)
		unless favorite_show.save
			@alert = favorite_show.errors.full_messages.join(',')
		end
	end

	def destroy
		@show = Show.find_by(id: params[:id])
		favorite_show = current_user.favorite_user_shows.find_by(show_id: @show.id)
		unless favorite_show.destroy
			@alert = favorite_show.errors.full_messages.join(',')
		end
	end

	def check_user
	  return if user_signed_in?
	  redirect_to new_user_session_path, alert: 'You must log on to do favorite show.'
	end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
	def index
		@q = Show.ransack(params[:q])
		@shows = @q.result.includes(:channel)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/favorites/create.js.erb
<% if @alert.present? %>
	toastr.error('<%= @alert %>');
<% else %>
	toastr.success('<%= @show.name %> added in your favorites.');
<% end %>
$('#show_<%= @show.id%>').empty().append('<%= j render "/shows/favorites", show: @show %>');

app/views/favorites/destroy.js.erb
<% if @alert.present? %>
	toastr.error('<%= @alert %>');
<% else %>
	toastr.error('<%= @show.name %> removed from your favorites.');
<% end %>
$('#show_<%= @show.id%>').empty().append('<%= j render "/shows/favorites", show: @show %>');

app/views/layouts/_header.html.erb
<div class='header'>
	<% if user_signed_in? %>
		<div class='row pull-right'>
			<div class='col-sm-9'></div>
			<div class='col-sm-2'>
				<label class='userName'><%= current_user.email %></label>
			</div>
			<div class='col-sm-1'>
				<%= button_to 'Logout', destroy_user_session_url, method: :delete, class: 'btn btn-danger' %>
			</div>
		</div>
	<% else %>
		<%if params[:controller] == 'shows' || params[:controller] == 'favorites'%>
			<div class='row pull-right'>
				<div class='col-sm-10'></div>
				<div class='col-sm-1'>
					<%= link_to 'LogIn', new_user_session_url, class: 'btn btn-primary' %>
				</div>
				<div class='col-sm-1'>
					<%= link_to 'SignUp', new_user_registration_url, class: 'btn btn-success' %>
				</div>
			</div>
		<%else%>
			<div class='row pull-right'>
				<%= link_to 'HOME', root_url, class: 'btn btn-primary' %>
			</div>
		<% end %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChannelShowTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <div class='wrapper'>
      <% if flash[:alert].present? %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <% if flash[:notice].present? %>
        <div class="alert alert-success" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <%= render '/layouts/header'%>
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shows/_favorites.html.erb
<%if current_user&.added_in_favorites(show.id) %>
	<%= link_to favorite_path(show.id), method: :delete, remote: true, class: 'red' do %>
		<i class="fa fa-heart"></i>
	<% end %>
<% else %>
	<%= link_to favorites_path(show_id: show.id), method: :post, remote: true do %>
		<i class="fa fa-heart"></i>
	<% end %>
<% end %>

app/views/shows/_search_result.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Channel Name</th>
      <th>Show Name</th>
      <th>Show Start Time</th>
      <th>Show End Time</th>
      <th>Favorites</th>
    </tr>
  </thead>
  <tbody>
  	<% if shows.present? %>
	  	<% shows.each do |show| %>
	      <tr>
	        <td><%= show.channel.name%></td>
	        <td><%= show.name%></td>
	        <td><%= show.start_time.strftime('%d/%m/%Y %R')%></td>
		      <td><%= show.end_time.strftime('%d/%m/%Y %R')%></td>
		      <td id=<%='show_'+show.id.to_s%>>
		      	<%= render 'favorites', show: show %>
		      </td>
	      </tr>
	    <% end %>
    <% else %>
    	<tr col_span=4>
	      <td>No result found. Please try with other search.</td>
	    </tr>
    <% end %>
  </tbody>
</table>

app/views/shows/index.html.erb
<div class='row'>
	<%= search_form_for @q, remote: true do |f| %>
		<div class='row'>
		  <div class='col-sm-5'>
		  	<%= f.label 'Channel name or Show Name' %>
		  	<%= f.search_field :name_or_channel_name_cont, class: 'form-control' %>
			</div>
		  <div class='col-sm-5'>
		  	<%= f.label 'Search with show start time' %>
		  	<%= f.search_field :start_time_eq, class: 'form-control', id: 'datetimepicker' %>
		  </div>
		  <div class='col-sm-2'>
		  	<%= f.submit 'SEARCH', class: 'btn btn-primary', id: 'searchBtn' %>
		  </div>
		</div>
	<% end %>
</div>
<div class='search'>
	<h4><strong>Search Result</strong></h4>
	<div class='row' id='searchResult'>
		<%= render 'search_result', shows: @shows%>
	<div>
</div>

app/views/shows/index.js.erb
$('#searchResult').empty().append('<%= j render "search_result", shows: @shows %>');